version: '3.8'

services:
  web:
      container_name: web
      build: ./
      restart: always
      ports:
        - 8080:8080
      links:
        - db


  db:
    container_name: expensedb
    image: mysql
    environment:
      MYSQL_USER: "admin"
      MYSQL_ROOT_PASSWORD : "devenv22!"
    restart: always
    volumes:
      - ${HOME}/mysql-data/:/var/lib/mysql
    ports:
      - "3306:3306"

      